exclude: ^(src/third_party|src/bsp)
repos:
-   repo: https://github.com/sofarocean/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/sofarocean/pocc-pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: cppcheck
