#
# This is the reduced environment_ci.yml used for automated test/builds
# There is a primary conda environment.yml for development
# Do NOT FORGET to update both when making changes to this file
#
channels:
  - sofar_fw
  - conda-forge
  - memfault
  - defaults
dependencies:
  # Don't forget to update compiler version check when updating compiler here!
  # Change src/CMakeLists.txt
  - arm-none-eabi-gcc=10.3_2021.10
  # - multi-arch-gdb=11.2
  # - openocd-xpack=0.11.0_5
  - cmake-xpack=3.20.6_2
  - make=4.2.1
  - python=3.10.11
  - pyserial
  - cppcheck
  - pre_commit
  - pip
  - pip:
      - memfault-cli==0.17.0
      - python-dotenv
      - gitpython
      - pytest
      - cryptography>=2.6
      - intelhex
      - click
      - cbor2

  # - lcov=1.15
  - clang-tools=11.0.0
  # - cppcheck=2.1
  - gcovr
